// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHl6MR7aV0YjsWe7z-k4oIqloSnkF8YTE',
    appId: '1:622667795911:web:c08e3b3347fcf3823f1de2',
    messagingSenderId: '622667795911',
    projectId: 'carrimen-db76b',
    authDomain: 'carrimen-db76b.firebaseapp.com',
    storageBucket: 'carrimen-db76b.appspot.com',
    measurementId: 'G-JJSVSPE3Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcDmaqcDssa7W5wvPQ7Fubf7yep89Inc',
    appId: '1:622667795911:android:2a9f73167844f1bc3f1de2',
    messagingSenderId: '622667795911',
    projectId: 'carrimen-db76b',
    storageBucket: 'carrimen-db76b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt-T1yy22wrb_0mTayT3X77qfaXW6j3ZM',
    appId: '1:622667795911:ios:448b685e345dc5913f1de2',
    messagingSenderId: '622667795911',
    projectId: 'carrimen-db76b',
    storageBucket: 'carrimen-db76b.appspot.com',
    iosBundleId: 'com.example.carriMenUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt-T1yy22wrb_0mTayT3X77qfaXW6j3ZM',
    appId: '1:622667795911:ios:88e39b70101917793f1de2',
    messagingSenderId: '622667795911',
    projectId: 'carrimen-db76b',
    storageBucket: 'carrimen-db76b.appspot.com',
    iosBundleId: 'com.example.carriMenUserApp.RunnerTests',
  );
}
